"""The resolved Python environment of the experiments, and its lock file.

``requirements.txt`` pins only the project's direct dependencies; what they
pull in (contourpy, pillow, python-dateutil, tzdata, ...) is left to pip, so
two installs of it need not match. ``requirements-lock.txt`` at the
repository root pins the whole resolved set: the direct dependencies and
every distribution they require, transitively, as installed in the
environment the experiments ran in. It lists only that closure, not every
package the interpreter happens to carry, so it can be installed on its own:

    python -m pip install -r requirements-lock.txt

Every experiment sidecar records the same closure as it resolved at run
time (``dependency_closure``) together with the lock file's path, SHA-256
and whether the environment matched it (``lock_record``), so a reader can
tell an exact-environment run from one made against drifted packages.

The lock is resolved on one platform (its header names the Python, the
system and the machine). A pin with an environment marker applies only
where the marker holds -- ``read_lock`` evaluates it, as pip does -- so an
install from the lock on another platform still matches it; another Python
may pull in packages the lock does not list (``lock_record['unpinned']``).

Regenerate the lock after an upgrade, from the environment the experiments
run in:

    python environment_lock.py            (from CODE/)
"""

from __future__ import annotations

import hashlib
import os
import platform
import re
import sys
from importlib import metadata as md
from typing import Dict, List, Optional, Tuple

#: The project's direct dependencies, as ``requirements.txt`` names them.
DIRECT_DEPENDENCIES = ('numpy', 'scipy', 'pandas', 'matplotlib', 'openpyxl',
                       'reportlab', 'pytest')

_CODE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(_CODE_DIR)
LOCK_NAME = 'requirements-lock.txt'
LOCK_PATH = os.path.join(REPO_ROOT, LOCK_NAME)


def _canon(name: str) -> str:
    """PEP 503 normalized name."""
    out = name.strip().lower()
    for ch in ('_', '.'):
        out = out.replace(ch, '-')
    while '--' in out:
        out = out.replace('--', '-')
    return out


def _parse(req: str) -> Tuple[str, Optional[str]]:
    """``(name, marker)`` of a ``Requires-Dist`` string, or ``('', None)``
    for a requirement that applies only with an extra or does not apply to
    this interpreter. The marker is kept when it applies but names the
    platform, so the lock line can carry it."""
    try:
        from packaging.requirements import Requirement
    except ImportError:                                  # pragma: no cover
        name = req.split(';', 1)[0]
        for sep in ('[', '(', '<', '>', '=', '!', '~', ' '):
            name = name.split(sep, 1)[0]
        marker = req.split(';', 1)[1].strip() if ';' in req else None
        if marker and 'extra' in marker:
            return '', None
        return name.strip(), marker
    r = Requirement(req)
    if r.marker is None:
        return r.name, None
    if 'extra' in str(r.marker):
        return '', None
    if not r.marker.evaluate():
        return '', None
    return r.name, str(r.marker)


def dependency_closure(roots=DIRECT_DEPENDENCIES
                       ) -> Dict[str, Dict[str, Optional[str]]]:
    """``{normalized name: {'version': v, 'marker': m}}`` for the roots and
    every installed distribution they require, transitively, with this
    interpreter's environment markers applied and extras not followed. A
    root that is not installed maps to version ``None``."""
    out: Dict[str, Dict[str, Optional[str]]] = {}
    stack: List[Tuple[str, Optional[str]]] = [(r, None) for r in roots]
    while stack:
        name, marker = stack.pop()
        key = _canon(name)
        if key in out:
            continue
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            out[key] = {'version': None, 'marker': marker}
            continue
        out[key] = {'version': dist.version, 'marker': marker}
        for req in dist.requires or []:
            dep, m = _parse(req)
            if dep:
                stack.append((dep, m))
    return dict(sorted(out.items()))


def lock_text(closure: Optional[Dict] = None) -> str:
    """The lock file for ``closure`` (default: this environment's)."""
    closure = dependency_closure() if closure is None else closure
    lines = [
        '# Resolved environment of the experiments: the direct dependencies',
        '# of requirements.txt and everything they require, as installed.',
        '# Generated by CODE/environment_lock.py; do not edit by hand.',
        f'# Python {sys.version.split()[0]} on {platform.system()} '
        f'{platform.machine()}',
        '# Resolved there: a pin with an environment marker applies only',
        '# where the marker holds, and another Python or platform may pull',
        '# in packages this closure does not list.',
    ]
    for name, rec in closure.items():
        if rec['version'] is None:
            continue
        line = f"{name}=={rec['version']}"
        if rec.get('marker'):
            line += f" ; {rec['marker']}"
        lines.append(line)
    return '\n'.join(lines) + '\n'


def marker_applies(marker: Optional[str]) -> bool:
    """Whether a lock line's environment marker holds for this interpreter
    (no marker: it always does), evaluated as pip evaluates it. Without
    ``packaging`` the marker cannot be evaluated and the pin is counted."""
    if not marker:
        return True
    try:
        from packaging.markers import Marker
    except ImportError:                                  # pragma: no cover
        return True
    return bool(Marker(marker).evaluate())


def read_lock(path: str = LOCK_PATH,
              evaluate_markers: bool = True) -> Dict[str, str]:
    """``{normalized name: version}`` pinned by the lock file FOR THIS
    INTERPRETER: a pin whose environment marker is false here (the lock's
    ``colorama ; sys_platform == "win32"`` anywhere but Windows) is left
    out, as ``pip install -r`` leaves it out. ``evaluate_markers=False``
    returns every pin."""
    out: Dict[str, str] = {}
    with open(path, encoding='utf-8') as f:
        for raw in f:
            line = raw.split('#', 1)[0].strip()
            req, _, marker = line.partition(';')
            req, marker = req.strip(), (marker.strip() or None)
            if '==' not in req:
                continue
            if evaluate_markers and not marker_applies(marker):
                continue
            name, ver = req.split('==', 1)
            out[_canon(name)] = ver.strip()
    return out


def lock_header(path: str = LOCK_PATH) -> Dict[str, Optional[str]]:
    """``{'python', 'system', 'machine'}`` the lock was resolved on, from its
    ``# Python <version> on <system> <machine>`` line (None when absent)."""
    out: Dict[str, Optional[str]] = {'python': None, 'system': None,
                                     'machine': None}
    with open(path, encoding='utf-8') as f:
        for raw in f:
            m = re.match(r'#\s*Python\s+(\S+)\s+on\s+(\S+)\s+(\S+)\s*$',
                         raw.strip())
            if m:
                out.update(python=m.group(1), system=m.group(2),
                           machine=m.group(3))
                break
    return out


def this_platform() -> Dict[str, str]:
    """This interpreter in ``lock_header``'s terms."""
    return {'python': sys.version.split()[0], 'system': platform.system(),
            'machine': platform.machine()}


def lock_record(path: str = LOCK_PATH,
                closure: Optional[Dict] = None) -> Dict[str, object]:
    """What a sidecar records about the lock file: its path relative to the
    repository, its SHA-256, where it was resolved (``resolved_on``) and
    whether this interpreter is that one (``same_platform``), and whether
    every package it pins FOR THIS INTERPRETER (``read_lock``: pins whose
    marker is false here are not required) is installed at that version
    (``matches_environment``; ``mismatches`` lists the ones that are not).
    ``unpinned`` lists what this environment's closure holds that the lock
    does not pin -- empty on the platform the lock was resolved on, where
    ``exact`` (a match with nothing unpinned) says the environment is the
    lock's. ``{'path': ..., 'sha256': None}`` when the file is missing.

    The hash is taken over the file with LF line ends, so a checkout that
    converts them to CRLF (git's autocrlf on Windows) hashes the same."""
    try:
        rel = os.path.relpath(path, REPO_ROOT).replace(os.sep, '/')
    except ValueError:              # another drive: keep it as given
        rel = path
    if not os.path.exists(path):
        return {'path': rel, 'sha256': None, 'matches_environment': None,
                'mismatches': None}
    with open(path, 'rb') as f:
        digest = hashlib.sha256(f.read().replace(b'\r\n', b'\n')).hexdigest()
    closure = dependency_closure() if closure is None else closure
    have = {k: v['version'] for k, v in closure.items()}
    pinned = read_lock(path)
    mism = []
    for name, ver in pinned.items():
        if have.get(name) != ver:
            try:
                got = md.version(name)
            except md.PackageNotFoundError:
                got = None
            if got != ver:
                mism.append({'package': name, 'locked': ver, 'installed': got})
    unpinned = sorted(k for k, v in have.items()
                      if v is not None and k not in pinned)
    header = lock_header(path)
    here = this_platform()
    return {'path': rel, 'sha256': digest,
            'resolved_on': header,
            'same_platform': all(header[k] == here[k] for k in here),
            'matches_environment': not mism, 'mismatches': mism,
            'unpinned': unpinned, 'exact': not mism and not unpinned}


def main() -> int:
    text = lock_text()
    with open(LOCK_PATH, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    n = sum(1 for ln in text.splitlines() if ln and not ln.startswith('#'))
    print(f"wrote {LOCK_PATH} ({n} packages)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
